// Package main generated by tools. DO NOT EDIT!
package main

type ItemSorting struct {
	Key   string `form:"key" validate:"required,oneof=name price"`
	Order string `form:"order" validate:"required,oneof=asc desc"`
}
