// Package main generated by tools. DO NOT EDIT!
package main

type ItemSorting struct {
	Key   string `json:"key" validate:"required,oneof=name price"`
	Order string `json:"order" validate:"required,oneof=asc desc"`
}
