// Package main generated by tools. DO NOT EDIT!
package main

// ItemSorting is the sorting setting of items
type ItemSorting struct {
	// ItemSorting is the item key
	Key string `form:"key" validate:"required,oneof=name price"`
	// ItemSorting is the item order
	Order string `form:"order" validate:"required,oneof=asc desc"`
}
