//go:build tools
// +build tools

package main

import (
	"os"
	"reflect"

	"github.com/anqur/procstruct"
)

type Item struct {
	Name  string `json:"name" gorm:"column:name;not null;type:varchar(64)" validate:"required"`
	Price int32  `json:"price" gorm:"column:price;not null;type:int(10)" validate:"required"`
}

func main() {
	s := procstruct.
		File("main").
		Header("generated by tools. DO NOT EDIT!").
		Structs(
			procstruct.
				Struct("ItemSorting").
				Header("is the sorting setting of items").
				Field(
					"Key",
					reflect.TypeOf(""),
					"is the item key",
					procstruct.Tag().Comma("form").
						Key("key"),
					procstruct.Tag().CommaEqSpace("validate").
						Key("required").
						EntryString(
							"oneof",
							procstruct.Of(Item{}).
								TagValues("gorm", "column")...,
						),
				).
				Field(
					"Order",
					reflect.TypeOf(""),
					"is the item order",
					procstruct.Tag().Comma("form").
						Key("order"),
					procstruct.Tag().CommaEqSpace("validate").
						Key("required").
						Entry("oneof", "asc", "desc"),
				),
		)

	data := []byte(s.String())
	if err := os.WriteFile("model.go", data, 0644); err != nil {
		panic(err)
	}
}
